const TYPES = [
    'normal','fire','water','electric','grass','ice',
    'fighting','poison','ground','flying','psychic','bug',
    'rock','ghost','dragon','dark','steel','fairy'
];

const TYPE_COLORS = {
    normal:   '#A8A878',
    fire:     '#F08030',
    water:    '#6890F0',
    electric: '#F8D030',
    grass:    '#78C850',
    ice:      '#98D8D8',
    fighting: '#C03028',
    poison:   '#A040A0',
    ground:   '#E0C068',
    flying:   '#A890F0',
    psychic:  '#F85888',
    bug:      '#A8B820',
    rock:     '#B8A038',
    ghost:    '#705898',
    dragon:   '#7038F8',
    dark:     '#705848',
    steel:    '#B8B8D0',
    fairy:    '#EE99AC',
};

const TYPE_NAMES = {
    es: {
        normal:'Normal', fire:'Fuego',    water:'Agua',    electric:'Eléctrico',
        grass:'Planta',  ice:'Hielo',     fighting:'Lucha', poison:'Veneno',
        ground:'Tierra', flying:'Volador', psychic:'Psíquico', bug:'Bicho',
        rock:'Roca',     ghost:'Fantasma', dragon:'Dragón',   dark:'Siniestro',
        steel:'Acero',   fairy:'Hada'
    },
    en: {
        normal:'Normal', fire:'Fire',     water:'Water',   electric:'Electric',
        grass:'Grass',   ice:'Ice',       fighting:'Fighting', poison:'Poison',
        ground:'Ground', flying:'Flying', psychic:'Psychic',   bug:'Bug',
        rock:'Rock',     ghost:'Ghost',   dragon:'Dragon',     dark:'Dark',
        steel:'Steel',   fairy:'Fairy'
    }
};

// TYPE_CHART[defenderType][attackerType] = multiplier (Gen 6+ rules)
const TYPE_CHART = {
    normal:   {normal:1,   fire:1,   water:1,   electric:1,  grass:1,   ice:1,   fighting:2,  poison:1,   ground:1,  flying:1,  psychic:1,  bug:1,   rock:1,  ghost:0,  dragon:1,  dark:1,   steel:1,   fairy:1  },
    fire:     {normal:1,   fire:0.5, water:2,   electric:1,  grass:0.5, ice:0.5, fighting:1,  poison:1,   ground:2,  flying:1,  psychic:1,  bug:0.5, rock:2,  ghost:1,  dragon:1,  dark:1,   steel:0.5, fairy:0.5},
    water:    {normal:1,   fire:0.5, water:0.5, electric:2,  grass:2,   ice:0.5, fighting:1,  poison:1,   ground:1,  flying:1,  psychic:1,  bug:1,   rock:1,  ghost:1,  dragon:1,  dark:1,   steel:0.5, fairy:1  },
    electric: {normal:1,   fire:1,   water:1,   electric:0.5,grass:1,   ice:1,   fighting:1,  poison:1,   ground:2,  flying:0.5,psychic:1,  bug:1,   rock:1,  ghost:1,  dragon:1,  dark:1,   steel:0.5, fairy:1  },
    grass:    {normal:1,   fire:2,   water:0.5, electric:0.5,grass:0.5, ice:2,   fighting:1,  poison:2,   ground:0.5,flying:2,  psychic:1,  bug:2,   rock:1,  ghost:1,  dragon:1,  dark:1,   steel:1,   fairy:1  },
    ice:      {normal:1,   fire:2,   water:1,   electric:1,  grass:1,   ice:0.5, fighting:2,  poison:1,   ground:1,  flying:1,  psychic:1,  bug:1,   rock:2,  ghost:1,  dragon:1,  dark:1,   steel:2,   fairy:1  },
    fighting: {normal:1,   fire:1,   water:1,   electric:1,  grass:1,   ice:1,   fighting:1,  poison:1,   ground:1,  flying:2,  psychic:2,  bug:0.5, rock:0.5,ghost:1,  dragon:1,  dark:0.5, steel:1,   fairy:2  },
    poison:   {normal:1,   fire:1,   water:1,   electric:1,  grass:0.5, ice:1,   fighting:0.5,poison:0.5, ground:2,  flying:1,  psychic:2,  bug:0.5, rock:1,  ghost:1,  dragon:1,  dark:1,   steel:1,   fairy:0.5},
    ground:   {normal:1,   fire:1,   water:2,   electric:0,  grass:2,   ice:2,   fighting:1,  poison:0.5, ground:1,  flying:1,  psychic:1,  bug:1,   rock:0.5,ghost:1,  dragon:1,  dark:1,   steel:1,   fairy:1  },
    flying:   {normal:1,   fire:1,   water:1,   electric:2,  grass:0.5, ice:2,   fighting:0.5,poison:1,   ground:0,  flying:1,  psychic:1,  bug:0.5, rock:2,  ghost:1,  dragon:1,  dark:1,   steel:1,   fairy:1  },
    psychic:  {normal:1,   fire:1,   water:1,   electric:1,  grass:1,   ice:1,   fighting:0.5,poison:1,   ground:1,  flying:1,  psychic:0.5,bug:2,   rock:1,  ghost:2,  dragon:1,  dark:2,   steel:1,   fairy:1  },
    bug:      {normal:1,   fire:2,   water:1,   electric:1,  grass:0.5, ice:1,   fighting:0.5,poison:1,   ground:0.5,flying:2,  psychic:1,  bug:1,   rock:2,  ghost:1,  dragon:1,  dark:1,   steel:1,   fairy:1  },
    rock:     {normal:0.5, fire:0.5, water:2,   electric:1,  grass:2,   ice:1,   fighting:2,  poison:0.5, ground:2,  flying:0.5,psychic:1,  bug:1,   rock:1,  ghost:1,  dragon:1,  dark:1,   steel:2,   fairy:1  },
    ghost:    {normal:0,   fire:1,   water:1,   electric:1,  grass:1,   ice:1,   fighting:0,  poison:0.5, ground:1,  flying:1,  psychic:1,  bug:0.5, rock:1,  ghost:2,  dragon:1,  dark:2,   steel:1,   fairy:1  },
    dragon:   {normal:1,   fire:0.5, water:0.5, electric:0.5,grass:0.5, ice:2,   fighting:1,  poison:1,   ground:1,  flying:1,  psychic:1,  bug:1,   rock:1,  ghost:1,  dragon:2,  dark:1,   steel:1,   fairy:2  },
    dark:     {normal:1,   fire:1,   water:1,   electric:1,  grass:1,   ice:1,   fighting:2,  poison:1,   ground:1,  flying:1,  psychic:0,  bug:2,   rock:1,  ghost:0.5,dragon:1,  dark:0.5, steel:1,   fairy:2  },
    steel:    {normal:0.5, fire:2,   water:1,   electric:1,  grass:0.5, ice:0.5, fighting:2,  poison:0,   ground:2,  flying:0.5,psychic:0.5,bug:0.5, rock:0.5,ghost:1,  dragon:0.5,dark:1,   steel:0.5, fairy:0.5},
    fairy:    {normal:1,   fire:1,   water:1,   electric:1,  grass:1,   ice:1,   fighting:0.5,poison:2,   ground:1,  flying:1,  psychic:1,  bug:0.5, rock:1,  ghost:1,  dragon:0,  dark:0.5, steel:2,   fairy:1  },
};

const PK_SLUG_EXCEPTIONS = {
    tapukoko:                   'tapu-koko',
    tapulele:                   'tapu-lele',
    tapubulu:                   'tapu-bulu',
    tapufini:                   'tapu-fini',
    'dudunsparce+threesegment': 'dudunsparce-three-segment',
    'ogerpon+cornerstone':      'ogerpon-cornerstone-mask',
    'calyrex+icerider':         'calyrex-ice',
    'calyrex+shadowrider':      'calyrex-shadow',
    darmanitan:                 'darmanitan-standard',
    'darmanitan+galarice':      'darmanitan-galar-standard',
    'darmanitan+galaricefire':  'darmanitan-galar-zen',
    eiscue:                     'eiscue-ice',
    'eiscue+noice':             'eiscue-noice',
    'kyurem+blackoverdrive':    'kyurem-black',
    'kyurem+whiteoverdrive':    'kyurem-white',
    'necrozma+dawnwings':       'necrozma-dawn',
    'necrozma+duskmane':        'necrozma-dusk',
    'pikachu+alolacap':         'pikachu-alola-cap',
    'pikachu+hoenncap':         'pikachu-hoenn-cap',
    'pikachu+kaloscap':         'pikachu-kalos-cap',
    'pikachu+originalcap':      'pikachu-original-cap',
    'pikachu+sinnohcap':        'pikachu-sinnoh-cap',
    'pikachu+unovacap':         'pikachu-unova-cap',
    'pikachu+rockstar':         'pikachu-rock-star',
    'pikachu+popstar':          'pikachu-pop-star',
    'squawkabilly+blue':        'squawkabilly-blue-plumage',
    'squawkabilly+green':       'squawkabilly-green-plumage',
    'squawkabilly+white':       'squawkabilly-white-plumage',
    'squawkabilly+yellow':      'squawkabilly-yellow-plumage',
    'tauros+paldeacombat':      'tauros-paldea-combat-breed',
    'tauros+paldeablaze':       'tauros-paldea-blaze-breed',
    'tauros+paldeaaqua':        'tauros-paldea-aqua-breed',
    'toxtricity+lowkey':        'toxtricity-low-key',
    'basculin+white':           'basculin-white-striped',
    'basculin+red':             'basculin-red-striped',
    'basculin+blue':            'basculin-blue-striped',
    toxtricity:                 'toxtricity-amped',
    'toxtricity+amped':         'toxtricity-amped',
    'zygarde+100':              'zygarde-complete',
    'minior+meteor':            'minior-red-meteor',
    morpeko:                    'morpeko-full-belly',
    aegislash:                  'aegislash-shield',
    basculegion:                'basculegion-male',
    deoxys:                     'deoxys-normal',
    dudunsparce:                'dudunsparce-two-segment',
    enamorus:                   'enamorus-incarnate',
    frillish:                   'frillish-male',
    giratina:                   'giratina-altered',
    gourgeist:                  'gourgeist-average',
    indeedee:                   'indeedee-male',
    jellicent:                  'jellicent-male',
    keldeo:                     'keldeo-ordinary',
    landorus:                   'landorus-incarnate',
    lycanroc:                   'lycanroc-midday',
    maushold:                   'maushold-family-of-three',
    meowstic:                   'meowstic-male',
    nidoran:                    'nidoran-f',
    oinkologne:                 'oinkologne-male',
    oricorio:                   'oricorio-baile',
    palafin:                    'palafin-zero',
    pumpkaboo:                  'pumpkaboo-average',
    pyroar:                     'pyroar-male',
    shaymin:                    'shaymin-land',
    tatsugiri:                  'tatsugiri-curly',
    thundurus:                  'thundurus-incarnate',
    tornadus:                   'tornadus-incarnate',
    urshifu:                    'urshifu-single-strike',
    wishiwashi:                 'wishiwashi-solo',
    wormadam:                   'wormadam-plant',
    typenull:                   'type-null',
    greattusk:                  'great-tusk',
    screamtail:                 'scream-tail',
    brutebonnet:                'brute-bonnet',
    fluttermane:                'flutter-mane',
    slitherwing:                'slither-wing',
    sandyshocks:                'sandy-shocks',
    roaringmoon:                'roaring-moon',
    irontreads:                 'iron-treads',
    ironbundle:                 'iron-bundle',
    ironhands:                  'iron-hands',
    ironjugulis:                'iron-jugulis',
    ironmoth:                   'iron-moth',
    ironthorns:                 'iron-thorns',
    ironvaliant:                'iron-valiant',
    gougingfire:                'gouging-fire',
    ragingbolt:                 'raging-bolt',
    ironboulder:                'iron-boulder',
    ironcrown:                  'iron-crown',
    walkingwake:                'walking-wake',
    ironleaves:                 'iron-leaves',
    bramaluna:                  'roaring-moon',
    colagrito:                  'scream-tail',
    colmilargo:                 'great-tusk',
    electrofuria:               'raging-bolt',
    ferrocuello:                'iron-jugulis',
    ferrodada:                  'iron-treads',
    ferromole:                  'iron-boulder',
    'ferropúas':                'iron-thorns',
    'ferropaladín':             'iron-valiant',
    ferropalmas:                'iron-hands',
    ferropolilla:               'iron-moth',
    ferrosaco:                  'iron-bundle',
    ferrotesta:                 'iron-crown',
    ferroverdor:                'iron-leaves',
    flamariete:                 'gouging-fire',
    furioseta:                  'brute-bonnet',
    melenaleteo:                'flutter-mane',
    ondulagua:                  'walking-wake',
    pelarena:                   'sandy-shocks',
    reptalada:                  'slither-wing',
};

const SKIN_SLUG_MAP = { hisuian: 'hisui' };

function toPokeApiSlug(name, skin) {
    const key = skin ? `${name}+${skin}` : name;
    if (PK_SLUG_EXCEPTIONS[key]) return PK_SLUG_EXCEPTIONS[key];
    const base = name
        .replace(/'/g, '')
        .replace(/\./g, '')
        .replace(/\s+/g, '-')
        .replace(/_/g, '-');
    if (!skin) return base;
    const skinSlug = (SKIN_SLUG_MAP[skin] ?? skin).replace(/\s+/g, '-').replace(/_/g, '-');
    return `${base}-${skinSlug}`;
}
